version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.4
    - 24.1.5
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@actions/io"
    versions:
    - 1.0.2
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: eslint-plugin-github
    versions:
    - 4.1.1
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: handlebars
    versions:
    - 4.7.6
    - 4.7.7
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: jest-circus
    versions:
    - 26.6.3
  - dependency-name: "@actions/core"
    versions:
    - 1.2.6
  - dependency-name: "@actions/github"
    versions:
    - 4.0.0
  - dependency-name: "@zeit/ncc"
    versions:
    - 0.22.3
  - dependency-name: ts-jest
    versions:
    - 24.3.0
