name: 'Android NDK toolchain Setup'
description: 'Setup Android NDK for native libs generation'
author: 'ravinderjangra'
inputs:
  api:
    description: 'Android API'
    default: '21'
    required: true
  arch:
    description: 'Platform arch'
    required: true
  install-location:
    description: 'Path to use for NDK toolchain'
    required: true
  force:
    description: 'Force install toolchain'
    default: 'false'
    required: false
  add-to-path:
    description: 'Add toolchain to the path'
    default: 'true'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
